// <auto-generated />
using System;
using AccountService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Infrastructure.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20251227013500_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Domain.Entities.ProfileTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("completed_projects")
                        .HasColumnType("integer");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("header_url")
                        .HasColumnType("text");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("profileTable");
                });

            modelBuilder.Entity("AccountService.Domain.Entities.SkillsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("verified")
                        .HasColumnType("boolean");

                    b.Property<int>("years_of_expirience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("skillsTable");
                });

            modelBuilder.Entity("AccountService.Domain.Entities.UsersTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_verified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("photo_url")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telegram_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("userTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0491979d-08ee-4f4e-b617-c794c2d38453"),
                            created_at = new DateTime(2025, 12, 27, 1, 35, 0, 304, DateTimeKind.Utc).AddTicks(5133),
                            first_name = "Антон",
                            is_verified = true,
                            last_name = "(Study)",
                            roles = new[] { "Freelancer" },
                            status = "offline",
                            telegram_id = "1006365928",
                            username = "studywhite"
                        });
                });

            modelBuilder.Entity("AccountService.Domain.Entities.ProfileTable", b =>
                {
                    b.HasOne("AccountService.Domain.Entities.UsersTable", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AccountService.Domain.Entities.ProfileTable", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Domain.Entities.SkillsTable", b =>
                {
                    b.HasOne("AccountService.Domain.Entities.UsersTable", "User")
                        .WithMany("Skills")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Domain.Entities.UsersTable", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
